export const ROUTES = {
  LOGIN: '/login',
  REGISTER: '/register',
  DASHBOARD: '/dashboard',
  INSTITUTIONS: '/institutions',
  INSTITUTION_NEW: '/institutions/new',
  INSTITUTION_DETAIL: '/institutions/:id',
  CLASSES: '/classes',
  CLASS_NEW: '/classes/new',
  CLASS_DETAIL: '/classes/:id',
  CONTRACTS: '/contracts',
  CONTRACT_NEW: '/contracts/new',
  CONTRACT_DETAIL: '/contracts/:id',
  AGENDA: '/agenda',
  SESSIONS: '/sessions',
  SESSION_NEW: '/sessions/new',
  SESSION_DETAIL: '/sessions/:id',
  PROFILE: '/profile',
} as const
